### ISSUE TITLE
Not trusting wildcard certificates

### ISSUE THREAD

**Issue by narcisgarcia** [gobby/gobby#10]
http://gobby.0x539.de/trac/ticket/613

Although the first time the user has accepted the SSL certificate, on next connections Gobby still warns as a not secure connection:

The connection to host "gobby.example.net" is not considered secure

The hostname of the server, "gobby.example.net", does not match the hostname the certificate is issued to, "*.example.net".

»View certificate

Do you want to continue the connection to host gobby.example.net?

**Comment by aburgm** [comment]
This should be fixed. Please reopen if it is still a problem.

**Comment by narcisgarcia** [comment]
Since which version should this be fixed?
Are new versions available in Ubuntu/Debian repositories?

**Comment by aburgm** [comment]
I'd expect it to work properly in Gobby 0.5.0. Debian Jessie has it.
