### ISSUE TITLE
external requiest for a minimal AppData change

### ISSUE THREAD

**Issue by herrold** [gobby/gobby#117]
This email crossed the mailing list.  Stuffing here to remind to do it

Date: Fri, 27 Nov 2015 09:29:08
From: "Richard Hughes (semi-automated)" <autohughski@gmail.com>
To: obby-users@list.0x539.de
Subject: obby] Additions required to the AppData file

... 
versions of the appstream-builder (the program used by distributions to merge
all the AppData files in packages into AppStream metadata) we're going to be
running a lot less crazy plugins. At the moment we're doing things like
parsing .gir files, running nm on binaries and looking up things from arrays
of hardcoded data just so we can try and work out what kudos the application
deserves. This doesn't scale, and means the machine generating the metadata
needs to have all kinds of extra build tools installed.

So, what do I want you to do? Basically, I would like you to:

Add the following data into gobby-0.5.appdata.xml

<blockquote>
  &lt;kudos&gt;<br>
    &lt;kudo&gt;HiDpiIcon&gt;/kudo&gt;<br>
    &lt;kudo&gt;ModernToolkit&gt;/kudo&gt;<br>
  &lt;/kudos&gt;
</blockquote>

Of course, you don't have to do a release with this fix straight away, and if
you have a stable branch it would be a good thing to backport this as well.
Nothing bad will happen if we run the automated tools with the kudos already
set in the AppData file. If you think any of the other kudos might apply[1],
please email me back and we can discuss any new additions.

When you've changed the file and committed, please email me back and I'll
mark your application as completed. If you don't want to hear from me ever
again just edit the <update_contact> in the AppData file and change it to
somebody else. I'm not planning on emailing any of you again this year, so
don't worry about me spamming you with even more work to do. If you don't add
the manual <kudos> then your application will still be visible in the various
software centers, but it may loose some of the stars it got auto-assigned.

[1] https://git.gnome.org/browse/gnome-software/plain/doc/kudos.md

**Comment by aburgm** [comment]
Did this already, see 61077e4.

**Comment by herrold** [comment]
thanks -- I had pulled and looked and missed it.  Sorry for the noice
