### ISSUE TITLE
gobby.0x539.de seems dead

### ISSUE THREAD

**Issue by mcepl** [gobby/gobby#135]
https://github.com/gobby/gobby/wiki claims:
```
We are also running a publicly available "playground" server that you are free to use.
It is available at gobby.0x539.de, which gobby can connect to.
```
The server seems to be dead (at least I cannot connect to it with gobby05-0.5.0-6.el7.x86_64 from Fedora packages).

**Comment by aburgm** [comment]
Yes, unfortunately the server is not running at the moment--I removed that statement.
