### ISSUE TITLE
how do I share with users over web? is there a public gobby server to connect to?

### ISSUE THREAD

**Issue by markmark1** [gobby/gobby#147]
is there a public gobby server to connect to? this needs to be in ui - it is not in subethaedit as well 👍

**Comment by markmark1** [comment]
are there any public hosts to connect to

**Comment by tyll** [comment]
Fedora hosts a public Gobby server:
https://fedoraproject.org/wiki/Gobby

**Comment by pkern** [comment]
I would not want to advertise a particular public server here so that users flock there. Some public servers exist but they are mostly offered by a community for a particular use/community. We no longer offer a project one, unfortunately.
