### ISSUE TITLE
how do I use it it seems unusable

### ISSUE THREAD

**Issue by markmark1** [gobby/gobby#148]
how do I use it ? how to share and edit docs? in connect to server

is It smb://76.12.20.49:6522

**Comment by markmark1** [comment]
are there any public hosts to connect to
whats format to give
gobby -c 10.1.2.194 doesn't work
nor does

gobby -c gobby.myserv.com

how to specify port

**Comment by tyll** [comment]
This seems to be a duplicate of #147

**Comment by pkern** [comment]
You need to host a server or connect to some kind of public one. In terms of command-line arguments this should work:

`gobby infinote://gobby.example.org`
