### ISSUE TITLE
Request not to use autogen during compilation

### ISSUE THREAD

**Issue by spartrekus** [gobby/gobby#163]
Hello,

I would be a good idea to remove autogen from compilation. 

cmake, autogen,... are not the best method for compilation.
more reading  https://suckless.org/sucks/

It would be good to have a clean and reliable compilation methods. 
It implies simplifying a bit on the code for wide spread user compilations for Everyone !

Thank you

**Comment by pkern** [comment]
ITYM autotools. I don't think linking to rants that include core libraries like glib are helpful. Apart from the fact that it proposes make, which is exactly what autotools is using. I actually made meson work for libinfinity but didn't submit the merge request yet. As-is I don't think your request is helpful.
