### ISSUE TITLE
ncurses editor for gobby-cli ?

### ISSUE THREAD

**Issue by spartrekus** [gobby/gobby#164]
Hello,

I would like to use the terminal as well over the SSH connection. 

Ideally would be maybe a sort of VIM that would connect on GOBBY Headless server (infinoted gobby headless).

For a small first attempt, it is possible to make a small editor Gobby-cli (it would be about 2000-4000 lines max). 

thank you and kind regards

**Comment by pedro-nonfree** [comment]
We need this tonight!

**Comment by pedro-nonfree** [comment]
it already exists!

in debian: `sudo apt install infinoted`

use server in tls or not https://wiki.archlinux.org/index.php/Gobby

**Comment by pkern** [comment]
That's what it originally started out from. But these days, someone could build it on top of infinote, but it's out of scope for this project.
