### ISSUE TITLE
The features.hpp is missing

### ISSUE THREAD

**Issue by ikwabe** [gobby/gobby#165]
The file included in your project i.e features.hpp  is missing when compiling the project, can I get a help please.. ?

#include "features.hpp"
#include "application.hpp"

int main(int argc, char* argv[])
{
	Glib::RefPtr<Gio::Application> application =
		Gobby::Application::create();

	const int result = application->run(argc, argv);

	// In GTK+ 3.12, there is a reference leak present which makes us
	// end up with one too much reference on the application object.
	// This bug was fixed for GTK+ 3.14.
	// https://bugzilla.gnome.org/show_bug.cgi?id=730383
	//
	// We need the application object to be finalized correctly, so that
	// its destructor runs and the preferences are serialized to disk.
	// Therefore, this hack makes sure that the application object ends up
	// with the expected reference count at this point.
	if(G_OBJECT(application->gobj())->ref_count > 1)
		application->unreference();

	return result;
}

**Comment by aburgm** [comment]
features.hpp is generated, you need to run the configure script before building

**Comment by ikwabe** [comment]
![gobby](https://user-images.githubusercontent.com/31654868/42095628-d0263c42-7bbb-11e8-996b-f01d48724cc7.PNG)

It doesnt connect to the server, tell me what to do?

**Comment by Wiadomy** [comment]
You need to host your own server, I think.
