### ISSUE TITLE
Mention what cellphone users are to do

### ISSUE THREAD

**Issue by jidanni** [gobby/gobby#169]
User has only brought a cellphone to a conference.
The cellphone is running Android or IOS.
The user is instructed to connect to Gobby.
User Googles and cannot find any workarounds for even a read-only web based version etc.

Therefore please on e.g., https://github.com/gobby/gobby/wiki mention: Cellphone users: we are working on it. Or Cellphone users: there is presently no solution. Anyway mention something even that there is no solution.

**Comment by pkern** [comment]
Gobby can do continuous web exports. So there is a solution. And no, we are not working on more support.

**Comment by jidanni** [comment]
I was just at DebConf18. All the other users were cheerily typing on
their laptops. But I alas was left looking over their shoulders, as
nobody knew what I should do with my cellphone.

So maybe document what URL one should type to see a even read-only
version of what other people are seeing. Thanks.

**Comment by pkern** [comment]
https://wiki.debian.org/gobby.debian.org (linked to from http://gobby.debian.org) literally has the link

**Comment by jidanni** [comment]
Maybe on  https://github.com/gobby/gobby/wiki say:

> Q: What if I don't have Linux, etc. but only a cellphone?
> A: No worry. Just check the site where you were told to connect to,
> there will probably be an 'exports' folder where you can at least find a read-only copy of what you were told to read, e.g.,  https://gobby.debian.org/export/debconf18/bof/diversity-team !

Note: many users are told "use gobby" and will then Google for Gobby, ending up on https://github.com/gobby/gobby/wiki and not on any individual Gobby instance.

**Comment by pkern** [comment]
Yeah, but I don't think it makes sense to link to a specific instance and print their instructions. That's for the organizers to do, really.

**Comment by pkern** [comment]
Yeah, but I don't think it makes sense to link to a specific instance and print their instructions. That's for the organizers to do, really.
