### ISSUE TITLE
Missing HTTP Charset on export

### ISSUE THREAD

**Issue by jidanni** [gobby/gobby#170]
Please set a HTTP Charset
```
$ GET -SU https://gobby.debian.org/export/debconf18/bof/diversity-team
User-Agent: lwp-request/6.35 libwww-perl/6.35

200 OK
[please feel free to fix the notes, use markdown <3]

Outcomes from last year
```
Else any Unicode symbols will be misinterpreted by the browser.

**Comment by jidanni** [comment]
I suppose this is produced by the gobby program and not something Debian has rigged up by themselves.

**Comment by pkern** [comment]
This is not support for Debian's instance of Gobby.
