### ISSUE TITLE
Can't download Windows Gobby installer

### ISSUE THREAD

**Issue by dalaeance** [gobby/gobby#178]
Whenever I try, I get the error: "You don't have permission to access /gobby/gobby-stable.exe on this server."
http://releases.0x539.de/gobby/gobby-stable.exe

**Comment by NK-Analyst** [comment]
Hi, @dalaeance .
Use this link http://releases.0x539.de/gobby/ and download file gobby-0.5.0.exe.

**Comment by dalaeance** [comment]
Thanks! That worked. Really not sure why it didn't cross my mind to back up to the folder storing the file.

**Comment by NK-Analyst** [comment]
At the present time I can't change materials in this repo. But I'll think of something.
