### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by mweinelt** [gobby/gobby#188]
In https://github.com/gobby/gobby/pull/184 a security vulnerability in gobby was fixed. I think this warrants a release, to make distributions aware their packaging might be outdated.

What keeps you from pushing out a new release at this time?

**Comment by aburgm** [comment]
I shall get to it on the weekend.

For my own education, how is #184 a security vulnerability? It's a null pointer dereference bug (that cannot be triggered remotely)... can it be used to gain elevated privileges or access to unauthorized access to files/data of the user running Gobby? At the moment I only see it as a simple crash bug.

**Comment by mweinelt** [comment]
I was asking from the PoV that this got a CVE assigned, so distro packagers will need to check up on the project and find the relevant patch and apply it to their distro version, which may or may not be quite old.

It is always harder to update a package, when patches need to be backported on the distro side, or if we have to track project versions by git commit, because distro maintainers aren't always well aware of everything going on in a project.

**Comment by pkern** [comment]
Sadly the incentives around CVEs are confusing at this point. This is not to say that there should be another release (as I also don't want to maintain the git snapshot in Debian for forever), but this was not a bug that necessarily should have gotten one in the first place.

**Comment by aburgm** [comment]
0.6.0 is out. For what it's worth, the bug in #184 was not even present in the previously released version. ;)
