### ISSUE TITLE
Win OS Installer Link Broken

### ISSUE THREAD

**Issue by tajmone** [gobby/gobby#200]
The download link for the Windows installer is broken, it points to a 404 "Page Not Found" error:

https://linkify.me/mBh4zm8

**Comment by pkern** [comment]
Where did you get that link from?

**Comment by tajmone** [comment]
From the repo Wiki:

https://github.com/gobby/gobby/wiki/Download

In fact I don't know why it's there, since the releases page contains the binary, but it needs to be fixed if people rely on the Wiki.

**Comment by pkern** [comment]
Sigh, I hope no-one was compromised by a fake installer. I have deleted the link and made the wiki read-only.

**Comment by tajmone** [comment]
Yes, that's a good idea, especially since Gobby has been stable for so long and doesn't need maintenance.

Thanks, great work! (really enjoying Gobby on my personal FreedomBox)
