### ISSUE TITLE
Settings schema 'de.0x539.gobby.preferences' is not installed

### ISSUE THREAD

**Issue by ryandesign** [gobby/gobby#201]
I'm attempting to update libinfinity and gobby in MacPorts to the latest versions. I've succeeded in building libinfinity 0.7.2 and gobby 0.6.0 but it fails to run for me on macOS 12:

```
% gobby-0.5      

(<unknown>:56078): GLib-GIO-ERROR **: 16:15:18.187: Settings schema 'de.0x539.gobby.preferences' is not installed
zsh: trace trap  gobby-0.5
```

**Comment by ryandesign** [comment]
I don't have a good understanding of GLib/GIO but I think I have now understood what it wants. The solution was to run `glib-compile-schemas` after installing gobby.

gobby did install the file /opt/local/share/glib-2.0/schemas/de.0x539.gobby.gschema.xml. That file does contain the string `schema="de.0x539.gobby.preferences"` which makes me think that's the file we're talking about. There are other *.gschema.xml files from other programs in that directory which makes me think it's in the right directory. It occurred to me that there might be some kind of indexing process that needs to be run to inform GLib/GIO of the new file, which led me to find `glib-compile-schemas`.

gobby's build process does run `glib-compile-schemas` automatically, but MacPorts tells all ports to install their files into a staging area (by setting `DESTDIR`); then, after installation, MacPorts catalogs what's in the staging area before installing it to the final location. This means that when the gobby Makefile runs `glib-compile-schemas` during its install process, the gobby gschema is not yet in the place where `glib-compile-schemas` will find it, so it doesn't get included. MacPorts must run `glib-compile-schemas` itself after the installation process.

**Comment by pkern** [comment]
Ok, so a packaging issue. :)

Pretty sure that on Debian we run glib-compile-schemas as part of the build (dh_installgsettings) as well, and it will look in the staging directory. I'd have assumed that MacPorts has some kind of helper as well.

**Comment by ryandesign** [comment]
Right, I, the person updating the packaging of this software in MacPorts, was not aware that this additional step needed to be performed by MacPorts. Now that I've understood that this was needed, I've instructed MacPorts to do so.
