### ISSUE TITLE
Source build broken on FreeBSD

### ISSUE THREAD

**Issue by Rainbowisz** [gobby/gobby#23]
The FreeBSD port of Gobby is far behind current ( http://www.freshports.org/editors/gobby/ ) so I attempted to build from source.
After manually installing all dependencies, I attempted to build and install libinfinity-0.6.4
It appears the program relies on linuxisms, and during build, make (and gmake) exit with the error "/usr/bin/ld: cannot find -lresolv"
While I am by no means a programmer and cannot offer a patch nor advice for how to fix this, it appears the program simply relies on linuxisms , which is what's causing the issue here.
In the meantime, using wine or the linux compatibility layer appear to be suitable, if not ideal, as a workaround.

**Comment by aburgm** [comment]
It seems like in FreeBSD, libresolv is not needed and the resolver function are instead in libc. Unfortunately I don't have a FreeBSD around to test this, but I have attempted a fix in the "resolvcheck" branch in libinfinity here:

https://github.com/gobby/libinfinity/tree/resolvcheck

Before I push this to master, would you mind trying it out and see if it fixes the problem on FreeBSD?

**Comment by Rainbowisz** [comment]
Happy to. I pulled down the source from the branch and attempted to build.
./configure cuts out with the error checking for res_query... configure: error: res_query not provided by either libc or libresolv
By the way, I'd be happy to donate a FreeBSD development server to your project, if it would help the project with getting it running on FreeBSD (and perhaps even the project taking over the port, as it doesn't seem as though the current maintainer has any interest in following new releases very closely)

**Comment by aburgm** [comment]
Hmpf, Googling suggested that res_query() is available in libc on FreeBSD. Maybe it needs to be linked explicitly with -lc... can you maybe upload your config.log and then I'll see what to try next?

Libinfinity and Gobby are coded in a fairly portable way so I do not expect many problems in general that would require a FreeBSD development server. It would be useful however to implement certain platform-specific features, such as support for TCP keep-alives, which at the moment is only available for Windows and Linux (in the master branch only). Migrating the event loop from poll() to kqueue might be another such thing. I don't have much experience with FreeBSD myself, so I don't know how much effort it would be to maintain the port, so I can't really make any promises on that at this point.

**Comment by Rainbowisz** [comment]
Well, if you'd like, I'd be happy to donate a small server.
I figure if I can't contribute to projects with code, I can always help with resources!
And luckily, the FreeBSD project maintains a lot of detailed documentation (puts the arch wiki to shame, haha), so if you ever were interested in maintaining the port, it wouldn't be too difficult to get up to speed with packaging gobby and libinfinity up right for the OS. Honestly, if I can find the time, I might do it myself, if only because I hate seeing unmaintained ports (especially when the code mainlined has advanced so far beyond what's being made available in the port...)

link to config.log is here
http://pau.smsittech.com/~samantha/derpfiles/libinf.config.log

**Comment by aburgm** [comment]
Thanks for the config.log file, it looks like the configure check is missing some header files. I have updated the branch, can you try building again?

I can't promise to use the server at full capacity, but if that's fine with you, I'd be happy to have it. It would be nice to set up some sort of Continuous Integration, in a similar way that we are using travis for automated builds on Ubuntu. You can contact me privately at armin@arbur.net with more details if you like.

**Comment by Rainbowisz** [comment]
Awesome, I'm trying it now, and I'll report back.
I'll shoot you an email at some point this evening regarding the server.

**Comment by Rainbowisz** [comment]
libinfinity and related libraries built and installed correctly under FreeBSD 10.1 with the current patch you made, using gmake (it lags with make, which calls Clang/LLVM).
However, attempting to build the Gobby master branch looks for version 0.7 of those libraries.
Attempting to build from http://releases.0x539.de/gobby/gobby-0.5.0.tar.gz results in gobby saying it cannot find the libraries (of version 0.6), though they're installed in /usr/local/lib
http://pau.smsittech.com/~samantha/derpfiles/gobby5.config.log

**Comment by aburgm** [comment]
That sounds promising. I'll push the patch to master soon. Thanks for trying it out!

I don't know the situation on FreeBSD, but on most Linux systems, libraries installed in /usr/local are not by default picked up when configuring a package. Try `./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH` when configuring Gobby, to make it find libinfinity in /usr/local. To actually run Gobby once it has built, you might also need to add `/usr/local/bin` to $PATH and `/usr/local/lib` to $LD_LIBRARY_PATH.

The Gobby master branch requires the master branch for libinfinity, but I have developed the patch on top of the libinfinity-0.6 branch (since you were trying to install libinfinity-0.6 before). So taking the gobby 0.5.0 tarball is correct, or alternatively the gobby-0.5 branch from git.

I also got your email about the server. I'll reply later today or tomorrow to that, have to run soon!

**Comment by Rainbowisz** [comment]
Those directories are part of your PATH by default in FreeBSD (Ports installed always go in /usr/local/bin, and libs always go in /usr/local/lib) so it confuses me as to why it's not finding them.
Forcing pkg-config to look in /usr/local/lib worked, and again, building with gmake rather than make allowed the program to be built and installed.

**Comment by aburgm** [comment]
Okay, so this is solved then? Is it usual to have to use gmake instead of make, or is this something that can/should be fixed?

**Comment by Rainbowisz** [comment]
While make SHOULD work, it calls a different compiler than gmake, and some software prefers being built by GCC, which is when one would use gmake.

And yes, this is solved. Again, you've got my thanks!

**Comment by aburgm** [comment]
Libinfinity builds with clang on Ubuntu, so there should be no reason why it should not work on FreeBSD. Maybe something I can check when the development server is up :)
