### ISSUE TITLE
Copy and paste don't work in chat

### ISSUE THREAD

**Issue by ParkerJones** [gobby/gobby#53]
Copy and paste don't work in the chat pane, but do work in the editing pane.  It's really quite useful to be able to copy/paste into the chat window.  Gobby-0.4 used to do this just fine.

Can anyone else reproduce this?

Gobby 0.6 compiled from source on Xubuntu 64 bit 14.04LTS 
222e4377da23636ae91509688a92b11c13aa5b82 as subsequent commits no longer compile due to dependencies that cannot be satisfied

**Comment by aburgm** [comment]
This is probably a side effect from making the chat view not focusable (I think at the moment when clicking in the chat view, the focus is moved to the chat entry where you can type text). As a walk-around, you should be able to right-click and select copy. But I agree we should make Ctrl+C work.

For 222e437 and subsequent commits, you'll need [libinfinity](https://github.com/gobby/libinfinity) from master as well. Did you try with that?

**Comment by ParkerJones** [comment]
Yes I can confirm that right-click+copy indeed works.  Of course, Ctrl+C would be nice too.

>For 222e437 and subsequent commits, you'll need libinfinity from master as well. Did you try with that?

Yes I did, the problem is dependencies: glibmm-2.4 >= 2.40.0 giomm-2.4 >= 2.40.0
ii  libglibmm-2.4-1c2a:amd64                    2.39.93-0ubuntu1                           amd64        C++ wrapper for the GLib toolkit (shared libraries)
ii  libglibmm-2.4-dev:amd64                     2.39.93-0ubuntu1                           amd64        C++ wrapper for the GLib toolkit (development files)

**Comment by aburgm** [comment]
Interesting... I wonder why they have 2.39.93 and not 2.40 in Trusty. The new gobby might work with 2.39.93 just fine, you could change the requirement in configure.ac and try it out -- if it works I'll change it in git, too.

**Comment by ParkerJones** [comment]
Yes I also tried this.  It compiles successfully but I get the following runtime error.

```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gtk.Actions' on object at path /de/_0x539/gobby
```
I have no idea what that means though.

**Comment by aburgm** [comment]
I have not seen that error before. It sounds like something is inconsistent about the installation. Did you make sure all other gobby instances are closed, and maybe rebooted your system?

What happens if you run "dbus-monitor | grep gobby" in one terminal, and then start gobby in another. For me this prints messages like this:

```
signal sender=:1.80 -> dest=(null destination) serial=11 path=/de/_0x539/gobby; interface=org.gtk.Actions; member=Changed
   string "type='signal',sender=':1.80',interface='org.gtk.Actions',member='Changed',path='/de/_0x539/gobby'"
method call sender=:1.21 -> dest=:1.80 serial=882 path=/de/_0x539/gobby; interface=org.gtk.Actions; member=DescribeAll
   string "type='signal',sender=':1.80',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/de/_0x539/gobby',arg0='org.gtk.Application'"
   string "type='signal',sender=':1.80',interface='org.gtk.Actions',member='Changed',path='/de/_0x539/gobby/window/1'"
method call sender=:1.21 -> dest=:1.80 serial=885 path=/de/_0x539/gobby/window/1; interface=org.gtk.Actions; member=DescribeAll
```

**Comment by ParkerJones** [comment]
My system inconsistent?  Possible, but unlikely.  I only install from the ubuntu repositories and a few well-established ppas. I can't reboot my office workstation I'm afraid.

I cloned git head, modified the configure.ac as below
```
$ git diff configure.ac
diff --git a/configure.ac b/configure.ac
index 75dae93..c2e3fbc 100644
--- a/configure.ac
+++ b/configure.ac
@@ -40,7 +40,7 @@ case "$host_os" in
 esac
 AM_CONDITIONAL(WIN32, test x$win32 = xtrue)
 
-required_libs="libxml++-2.6 glibmm-2.4 >= 2.40.0 giomm-2.4 >= 2.40.0 libgsasl >= 0.2.21 gtkmm-3.0 >= 3.6.0 gtksourceview-3.0 >= 3.0.0"
+required_libs="libxml++-2.6 glibmm-2.4 >= 2.39.93 giomm-2.4 >= 2.39.93 libgsasl >= 0.2.21 gtkmm-3.0 >= 3.6.0 gtksourceview-3.0 >= 3.0.0"
 
 ###################################
 # Check for libraries.
```
Nevertheless, my dbus output is still different to yours
```
$ dbus-monitor | grep gobby
   string "de._0x539.gobby"
   string "de._0x539.gobby"
signal sender=:1.4529 -> dest=(null destination) serial=11 path=/de/_0x539/gobby; interface=org.gtk.Actions; member=Changed
   string "de._0x539.gobby"
   string "de._0x539.gobby"
^C
$
```

**Comment by aburgm** [comment]
> My system inconsistent? Possible, but unlikely.

I didn't mean with the system really, but rather with the Gobby installation. But I'm not sure. It could also have to do with one of the dependencies. I haven't seen this error before. Unfortunately, googling the error message is not very helpful.

**Comment by aburgm** [comment]
I have just pushed a fix into libinfinity which makes Ctrl+C work for the chat.

**Comment by ParkerJones** [comment]
Yes, I can confirm that Ctrl+C now works for the chat window.  Thank you for the fix, Armin.
