### ISSUE TITLE
Direct connection interface could be streamlined

### ISSUE THREAD

**Issue by ParkerJones** [gobby/gobby#54]
Opening a direct connection takes too many clicks:
1. Expand <Direct Connection>
2. Click to open Hostname dropdown menu
3. Select host
4. Click on host text
5. Press enter

Steps 4 and 5 are redundant, can we just connect at step 3. on selecting the host?

It might seem minor, but some of us do this several times a days, every day.  But then perhaps it's just me :-)

**Comment by aburgm** [comment]
This would be easy to implement. The disadvantage is that one cannot select a hostname and then modify it afterwards, and it would maybe not be what people typically expect from a combo box. So I'm not entirely sold on it.

I wonder why step 4. is necessary. Isn't the text entry focused after selecting a host? I suppose we could at least make that automatic.

For now, note you can also scroll through the recent hostname list with the up and down arrows, which might collapse steps 2-4 into one :). Step 1 can be quickly achieved with the alt+d shortcut, or ctrl+t opens a dialog with the same functionality.

**Comment by ParkerJones** [comment]
> Isn't the text entry focused after selecting a host?
Yes it's selected but hitting enter causes the dropdown box to open up again.  Is the behaviour different for you?

> note you can also scroll through the recent hostname list with the up and down arrows
Yes, I can scroll up and down and select one.  But as before hitting enter opens the box up again.  I have to click on the text to get a flashing cursor.

I appreciate this is just a little detail, but it does affect the overall polish of wonderful gobby :-)

**Comment by aburgm** [comment]
> Yes it's selected but hitting enter causes the dropdown box to open up again. Is the behaviour different for you?

I'll see what happens for me when I get home tonight. It doesn't sound right.

What usually works for me is pressing alt+d, pressing up/down, and pressing enter.

**Comment by aburgm** [comment]
> Yes it's selected but hitting enter causes the dropdown box to open up again. Is the behaviour different for you?

Yeah, it's the same behaviour for me. So I think what should be done is when selecting a host from the dropdown box the focus should be given to the text entry widget and not the arrow that brings up the dropdown box again. Do you agree?

> Yes, I can scroll up and down and select one. But as before hitting enter opens the box up again. I have to click on the text to get a flashing cursor.

However, I cannot reproduce this. When I'm in the text editing box and use the up and down arrays the focus stays in the text editing box, and pressing enter makes the connection. Can you confirm this is different for you?

**Comment by ParkerJones** [comment]
>>>note you can also scroll through the recent hostname list with the up and down arrows

>>Yes it's selected but hitting enter causes the dropdown box to open up again. Is the behaviour different for you?

>Yeah, it's the same behaviour for me. So I think what should be done is when selecting a host from the dropdown box the focus should be given to the text entry widget and not the arrow that brings up the dropdown box again. Do you agree?

I don't know.  I'm not a UI person at all, so I'm not a good person to ask. All I know is that it should be easier to open the same host.   If there's no obvious solution with the dropdown box, perhaps another approach is to keep the used hosts in the document browser?  Restarting gobby would show all the previous hosts in the document browser.

>> Yes, I can scroll up and down and select one. But as before hitting enter opens the box up again. I have to click on the text to get a flashing cursor.

>However, I cannot reproduce this. When I'm in the text editing box and use the up and down arrays the focus stays in the text editing box, and pressing enter makes the connection. Can you confirm this is different for you?

Yes I can confirm.  Just to be clear: I click on the down arrow that opens the list of hosts, I move between them with up and down arrow keys, to select I press enter.  At that point the open-box down arrow is still highlighted (dotted line). Hitting enter does not open the connection to the host but instead opens the dropdown box again.  To open the connection I have to click on the hostname again to put the focus there and then hot enter.  Hope that helps.

**Comment by aburgm** [comment]
> I click on the down arrow that opens the list of hosts, I move between them with up and down arrow keys, to select I press enter. At that point the open-box down arrow is still highlighted (dotted line)

Ah, so this is where the misunderstanding comes from. What I meant is: Without clicking on the arrow that opens the dropdown box, press the up and down arrow keys on the keyboard to cycle through recently used hosts.

> If there's no obvious solution with the dropdown box, perhaps another approach is to keep the previously used hosts in the document browser?

Something like this has actually been suggested before: being apple to "pin" hosts in the document browser such that they re-appear when Gobby is closed and re-opened. Actually #5 is a PR for that, but it wasn't quite ready to merge at the time and was not followed up since then, I think. I like that idea, maybe I'll try to set some time aside soon to get it ready.

**Comment by aburgm** [comment]
> Something like this has actually been suggested before: being apple to "pin" hosts in the document browser such that they re-appear when Gobby is closed and re-opened.

I have added this functionality. I consider this issue closed with that.
