### ISSUE TITLE
Links to Mailinglists referenced in README.MD dead

### ISSUE THREAD

**Issue by pintman** [gobby/gobby#55]
The links to the mailinglists that are referenced on the entry page are dead. Is there another place to find the mailinglists and their archives?

**Comment by aburgm** [comment]
There is an archive available at http://www.mail-archive.com/obby-announce@list.0x539.de/ and http://www.mail-archive.com/obby-users@list.0x539.de.

To subscribe and unsubscribe, one can send mail to obby-users-unsubscribe@list.0x539.de and obby-users-subscribe@list.0x539.de, respectively. I'll try to find out what happened to the web interface and update the README.md file then.

**Comment by pintman** [comment]
Great. Thanks for the links.

**Comment by aburgm** [comment]
@pkern, is there another website with the mailing lists somewhere, or should I just put the above email addresses in README.md?

**Comment by aburgm** [comment]
I updated the file with the above information.
