### ISSUE TITLE
gobby-0.5.0 build system doesn't provide exact switch to build docs

### ISSUE THREAD

**Issue by ssten** [gobby/gobby#62]
gobby-0.5.0 build system doesn't provide a switch to build docs.
Documentation is installed always depending on presence of app-text/gnome-doc-utils package.
So, if I have this package installed, gobby always installes doc, I can't say him not to do it.

It would be fine, if gobby's build system would provide an option, directly set installation of docs or skipping it.

**Comment by aburgm** [comment]
I added a build switch although I can't really think of a reason when you don't want docs to be built when you have the gnome-doc-utils package anyways...
