### ISSUE TITLE
Crash when attempting to connect to document

### ISSUE THREAD

**Issue by soportek** [gobby/gobby#63]
I can connect to my infinoted instance and view the list of documents and even use teh chat. But at the moment i attempt to view a document gobby crashes. I am running debian wheezy with gobby version 0.4.94-5 .

When running gobby from the terminal i receive the following output when it crashes.

** (gobby-0.5:4738): CRITICAL **: inf_user_get_status: assertion `INF_IS_USER(user)' failed
** (gobby-0.5:4738): CRITICAL **: inf_user_get_status: assertion `INF_IS_USER(user)' failed
** (gobby-0.5:4738): CRITICAL **: inf_user_get_name: assertion `INF_IS_USER(user)' failed
(gobby-0.5:4738): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::_S_construct null not valid
Trace/breakpoint trap

Any suggestions?

**Comment by aburgm** [comment]
This is probably fixed by bfd20c8. You could upgrade to 0.5.0, or cherry-pick that commit and apply it on top of 0.4.94.

**Comment by aburgm** [comment]
By the way, as a workaround, I would imagine that the following works: Open ~/.config/gobby/config.xml, and change the `show-document-userlist` setting from 1 to 0. Once the document is opened, you can show the user list again with Ctrl+F9.

**Comment by aburgm** [comment]
I think this is fixed. Please re-open if this still happens with 0.5.0.
