### ISSUE TITLE
gobby-0.5.0 build system does hardcoded AR calls

### ISSUE THREAD

**Issue by ssten** [gobby/gobby#78]
Gobby-0.5.0 build system does hardcoded AR calls that can be a problem when cross-compiling:

/var/tmp/portage/app-editors/gobby-0.5.0-r1/temp/build.log:
…
ar cru libgobby-util.a asyncoperation.o closebutton.o color.o config.o file.o groupframe.o historyentry.o i18n.o serialize.o uri.o
…

See https://bugs.gentoo.org/show_bug.cgi?id=444026 for details.

**Comment by aburgm** [comment]
What would be the preferred fix for this? Involving libtool?

We could switch to more modern non-recursive automake anyway, and then static archives would not be needed anyway at all.

**Comment by ssten** [comment]
New automake will be good I guess.

**Comment by aburgm** [comment]
I changed to use non-recursive automake. Static libraries are no longer generated during the build.
