### ISSUE TITLE
gobby-0.5.0 build system deps incompatible (GTK+ 2) default

### ISSUE THREAD

**Issue by ssten** [gobby/gobby#79]
gobby-0.5.0 has some GTK+3-only dependencies, but it's build system still expects GTK+2 default:

./configure --help
…
Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-gtk3             Builds gobby against GTK+ 3 instead of GTK+
                          2[[default=no]]
…

I think, it's a time to move this dependency from _optional_ dependencies list to strict check.

**Comment by aburgm** [comment]
Which are the GTK+3-only dependencies?

The Windows build of Gobby is made against GTK+2, so in principle there should not be any.

For the next Gobby version, GTK+2 support has been dropped anyway.

**Comment by ssten** [comment]
Oops.
Excuse me, that was my miss.
