### ISSUE TITLE
Font size should be adjustable with hotkeys

### ISSUE THREAD

**Issue by pkern** [gobby/gobby#83]
This is actually an ancient [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=681520) that still applies: A hotkey like Ctrl-+/- to adjust the font size would be helpful to make it easier to connect Gobby to a projector.

**Comment by aburgm** [comment]
This is already implemented in Gobby 0.5.0.

**Comment by pkern** [comment]
Ah, Ctrl-Alt-+/-. Chrome seems to accept both and I regularly only used Ctrl-+/- because of that. Thanks!
