### ISSUE TITLE
APPDATA is not the correct path for infinoted.conf on Windows

### ISSUE THREAD

**Issue by Sopor-** [gobby/gobby#88]
https://github.com/gobby/gobby/wiki/Dedicated-Server

You have written that the infinoted.conf will be in "%APPDATA%/infinoted.conf" but that is not true.
If i check my "%APPDATA%" it will point here:
"APPDATA=C:\Users\<username>\AppData\Roaming"
and i can find "infinoted.conf" here:
"c:\Users\<username>\AppData\Local\infinoted.conf".

"Local" is the same as: "%LOCALAPPDATA%" and you use that when you create the certs.

Btw, Windows use backslash, not forward slash :)

I also found a typo on the same page as above in the plugin section autosave:
"Save the douments periodically to the server's"
As you can see documents is missing a 'c'.

**Comment by aburgm** [comment]
Thanks, I fixed the page. Feel free to edit it yourself next time :)
